### ISSUE TITLE
[feature]-Suggestion to rename interface 'Repository

### ISSUE THREAD

**Issue by HankGuo93** [yamiew00/MongoGogo#1]
@yamiew00 
"Repository" is a specific term used in project layering. It is recommended to consider using a different name. 
:)

**Comment by yamiew00** [comment]
@HankGuo93 
Thanks for the suggestion, The term 'Repository' has been comprehensively renamed to 'Collection,' which better represents the meaning of the object itself. The relevant updates take effect starting from version 2.0.1.
